apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mysql-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  host: {{ .Values.mysql.host | b64enc }}
  rootPassword: {{ .Values.mysql.rootPassword | b64enc }}
  database: {{ .Values.mysql.database | b64enc }}
  user: {{ .Values.mysql.user | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}
