apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  skyline.yaml: |
    {{- toYaml .Values.skyline_settings | b64enc | nindent 4 }}
