apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: skyline-bootstrap
          image: "{{ .Values.bootstrapImage.repository }}:{{ .Values.bootstrapImage.tag }}"
          env:
            - name: KOLLA_BOOTSTRAP
              value: ""
          ports:
            - containerPort: {{ .Values.initContainerPort }}
          volumeMounts:
            - name: skyline-config
              mountPath: /etc/skyline/skyline.yaml
              subPath: skyline.yaml
      containers:
        - name: skyline-console
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: skyline-config
              mountPath: /etc/skyline/skyline.yaml
              subPath: skyline.yaml
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-mysql-credentials
                  key: host
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-mysql-credentials
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-mysql-credentials
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-mysql-credentials
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-mysql-credentials
                  key: password
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
      volumes:
        - name: skyline-config
          secret:
            secretName: {{ .Chart.Name }}-config
