apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-scripts
  labels:
    app: {{ .Chart.Name }}
data:
  _init-db.sh: |
{{ include "skyline-console.template.bin._init-db.sh" . | indent 4 }}
